# Updated deployment.yaml with init container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-app
  labels:
    app: text-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-app
  template:
    metadata:
      labels:
        app: text-app
    spec:
      initContainers:
      - name: init-db
        image: khutchi2/stepup:text-app
        command: ['python', '-c', 'import os; import psycopg2; conn = psycopg2.connect(os.environ["DATABASE_URL"]); cur = conn.cursor(); cur.execute("CREATE TABLE IF NOT EXISTS text_entries (id SERIAL PRIMARY KEY, content TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"); conn.commit(); cur.close(); conn.close(); print("Database initialized!")']
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
      containers:
      - name: web-app
        image: khutchi2/stepup:text-app
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"