# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres in base64
  password: cGFzc3dvcmQ=  # password in base64
  url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzOjU0MzIvdGV4dGRi  # postgresql://postgres:password@postgres:5432/textdb in base64